### ISSUE TITLE
target url issue

### ISSUE THREAD

**Issue by RafalMiszczuk** [SPQRInc/pagekit-redirect#1]
Hello,
I have problem with spqr/redirect. After upgrade extension, to version 1.0.1, input fields (select-link) disappeared. I can't change target url.

Reinstall extension doesn't solve the problem.

![redirect](https://user-images.githubusercontent.com/33953744/33203861-cedba242-d101-11e7-9c44-e197a81f41cb.jpg)

**Comment by ahoiroman** [comment]
Hi,

unfortunately I can not confirm this (see attached screencast).


Could you please do the following:

- Clear your browser's cache
- Clear Pagekit's cache
- If this does not help: Open the browser's error console and check out where the problem is.


![2017-11-24 10 35 41](https://user-images.githubusercontent.com/23051150/33204333-791ab936-d103-11e7-9662-acb61bac012b.gif)

**Comment by RafalMiszczuk** [comment]
I cleared cache. I'm using 4 different browser, and 2 OS. I'm install extension version 1.0.1 on different web page (never before, I don't install on this page redirect extension ) and problem is this same.

I think, is a CSS issue. I will try to find a solution on the weekend.
Could You please take a look.

![redirect-2](https://user-images.githubusercontent.com/33953744/33205097-fdea77da-d105-11e7-97e9-cf30be3caaa9.jpg)

**Comment by ahoiroman** [comment]
I will check that. I just wonder why I can not see that on all my browsers ;)

**Comment by ahoiroman** [comment]
Fixed it. Update is available via marketplace in a few minutes.

**Comment by RafalMiszczuk** [comment]
Thank You, it works great :)
