### ISSUE TITLE
Conflict

### ISSUE THREAD

**Issue by nickdring** [SPQRInc/pagekit-redirect#2]
Hi there, We have a conflict between the Tiny Editor and Rewrite URL. If the plugins are both active, on edit page, the text window does not appear.

**Comment by ahoiroman** [comment]
Hi Nick,

could you please provide more information? Please tell me, which error messages you see in your browser's JavaScript error console.

Thanks in advance :)

**Comment by angionisimone** [comment]
Hello,
Below the errors show in the console. Thank you

node-theme.js?v=01aa:51 [vue-loader] app/components/node-theme.vue: named exports in *.vue files are ignored.

(anonymous) @ node-theme.js?v=01aa:51


Use tinymce.min.js instead of tinymce.jquery.min.js.                             tinymce.jquery.min.js:1

Failed to load resource: the server responded with a status of 404 (Not Found)
       /tinymce/en_GB.js:1

Failed to load: /tinymce/en_GB.js                                             tinymce.jquery.min.js:9405

**Comment by ahoiroman** [comment]
I can not confirm this. I am running both extensions and TinyMCE is working fine.

But I'll release huge new update anyway, so I guess this could fix that issue, as it comes with some important fixes.

**Comment by nickdring** [comment]
Hi there, we haven't seen the update yet so we can try and resolve this issue. WHen do you think it will drop?
Cheers!

**Comment by ahoiroman** [comment]
Hi...  Actually I am very busy at the moment. I hope to get it done next Friday.

**Comment by ahoiroman** [comment]
Released version `2.0.0` today, which should solve this issue (if correctly configured). Feel free to reopen, if the problem still persists.
